<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>BinanceSignalMobile</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>Binance Signal</ApplicationTitle>
    <ApplicationId>com.local.binancesignal</ApplicationId>
    <ApplicationDisplayVersion>3.1.4</ApplicationDisplayVersion>
    <ApplicationVersion>314</ApplicationVersion>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.svg" Color="#0B0E11" />
    <MauiSplashScreen Include="Resources/Splash/splash.svg" Color="#0B0E11" BaseSize="128,128" />
    <MauiImage Include="Resources/Images/*" />
  </ItemGroup>
</Project>
